require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WolvesController do

  # This should return the minimal set of attributes required to create a valid
  # Wolf. As you add validations to Wolf, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WolvesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all wolves as @wolves" do
      wolf = Wolf.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wolves).should eq([wolf])
    end
  end

  describe "GET show" do
    it "assigns the requested wolf as @wolf" do
      wolf = Wolf.create! valid_attributes
      get :show, {:id => wolf.to_param}, valid_session
      assigns(:wolf).should eq(wolf)
    end
  end

  describe "GET new" do
    it "assigns a new wolf as @wolf" do
      get :new, {}, valid_session
      assigns(:wolf).should be_a_new(Wolf)
    end
  end

  describe "GET edit" do
    it "assigns the requested wolf as @wolf" do
      wolf = Wolf.create! valid_attributes
      get :edit, {:id => wolf.to_param}, valid_session
      assigns(:wolf).should eq(wolf)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wolf" do
        expect {
          post :create, {:wolf => valid_attributes}, valid_session
        }.to change(Wolf, :count).by(1)
      end

      it "assigns a newly created wolf as @wolf" do
        post :create, {:wolf => valid_attributes}, valid_session
        assigns(:wolf).should be_a(Wolf)
        assigns(:wolf).should be_persisted
      end

      it "redirects to the created wolf" do
        post :create, {:wolf => valid_attributes}, valid_session
        response.should redirect_to(Wolf.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wolf as @wolf" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wolf.any_instance.stub(:save).and_return(false)
        post :create, {:wolf => { "name" => "invalid value" }}, valid_session
        assigns(:wolf).should be_a_new(Wolf)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wolf.any_instance.stub(:save).and_return(false)
        post :create, {:wolf => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wolf" do
        wolf = Wolf.create! valid_attributes
        # Assuming there are no other wolves in the database, this
        # specifies that the Wolf created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wolf.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => wolf.to_param, :wolf => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested wolf as @wolf" do
        wolf = Wolf.create! valid_attributes
        put :update, {:id => wolf.to_param, :wolf => valid_attributes}, valid_session
        assigns(:wolf).should eq(wolf)
      end

      it "redirects to the wolf" do
        wolf = Wolf.create! valid_attributes
        put :update, {:id => wolf.to_param, :wolf => valid_attributes}, valid_session
        response.should redirect_to(wolf)
      end
    end

    describe "with invalid params" do
      it "assigns the wolf as @wolf" do
        wolf = Wolf.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wolf.any_instance.stub(:save).and_return(false)
        put :update, {:id => wolf.to_param, :wolf => { "name" => "invalid value" }}, valid_session
        assigns(:wolf).should eq(wolf)
      end

      it "re-renders the 'edit' template" do
        wolf = Wolf.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wolf.any_instance.stub(:save).and_return(false)
        put :update, {:id => wolf.to_param, :wolf => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wolf" do
      wolf = Wolf.create! valid_attributes
      expect {
        delete :destroy, {:id => wolf.to_param}, valid_session
      }.to change(Wolf, :count).by(-1)
    end

    it "redirects to the wolves list" do
      wolf = Wolf.create! valid_attributes
      delete :destroy, {:id => wolf.to_param}, valid_session
      response.should redirect_to(wolves_url)
    end
  end

end
